name: Scraper

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    scrape:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.11'
                  cache: 'pip'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements.txt
                  playwright install chromium
            
            - name: Run scraper
              env:
                ENVIRONMENT: production
                CLIENT: ${{ secrets.CLIENT }}
                DATABASE: ${{ secrets.DATABASE }}
                API_COLLECTION_SCRAPER: ${{ secrets.COLLECTION }}
              run: |
               python -m db.blue_archive_characters